# Generated by Django 3.1.1 on 2020-12-16 14:50

from django.db import migrations, models
import django.db.models.deletion
import jobmanager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default=None, max_length=100)),
                ('usrname', models.CharField(default=None, max_length=50, null=True)),
                ('requirements', models.TextField(default=None, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('email', models.EmailField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('github', models.URLField(blank=True, default=None, max_length=100, null=True)),
                ('resume', models.FileField(upload_to=jobmanager.models.uploadhere)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default=None, max_length=100)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobmanager.company')),
            ],
        ),
    ]
