# Generated by Django 3.1.1 on 2020-12-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='usrname',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
