# Generated by Django 3.1.1 on 2020-12-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanager', '0002_auto_20201217_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystudents',
            name='isselected',
            field=models.BooleanField(default=False),
        ),
    ]
